permalink: pretty
plugins:
  - jekyll-sitemap
exclude:
  - Gemfile
  - Gemfile.lock
  - makefile
  - vendor/
  
url: https://blog.carsonevans.ca

title: Carson's Blog
subtitle: Somewhat coherent tutorials about web stuff and things.
avatar: https://blog.carsonevans.ca/img/avatar-new.jpg

enable_disqus: true
disqus_shortname: carsonsblog

enable_googleanalytics: true
googleanalytics_id: UA-67307858-1
